### ISSUE TITLE
how to download data from 10Xgenomics 

### ISSUE THREAD

**Issue by worker000000** [johandahlberg/awesome-10x-genomics#4]
hi, there, can I ask you a question,thanks in advance.  how to download fastqs from th url https://support.10xgenomics.com/single-cell-gene-expression/datasets, thanks

**Comment by johandahlberg** [comment]
Hi!

I'm afraid I'm not sure what you mean. It appears that there are download links at the url you are referencing, if you are experiencing problems with those I'd suggest that you contact the 10x Genomics support and I'm sure they will be able to help you. To be clear, I'm in no way affiliated with 10x Genomics, I just maintain this list of software related to their platform out of curiosity. 

Cheers,
Johan
